# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b3d66d062f3e0a052311cec130a1ce4e116ffece1b711b48e7c84668bba182beff64d9bec6cc2ddd6eaecbce048dc94ed4dbbce5207d94e29c2df34cd412f854

test:
  secret_key_base: 031b5bdf85a7bc3a8aecc21f5b5b5ce943691e6ccd5ca75e3afa77e73a000e3d4277fc27cce48f1dde1f84aecf7957ae69727fb862a3e203f88a339cdca2ba05

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
